/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tercer_trimestre;

import datos.datos;
import java.sql.*;
import javax.swing.ButtonModel;
import metodo.*;

/**
 *
 * @author artur
 */
public class Billetes_Personas extends javax.swing.JFrame {

    /**
     * Creates new form Billetes_Personas
     */
    public Billetes_Personas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Text_Nombre = new javax.swing.JLabel();
        Text_Apellido1 = new javax.swing.JLabel();
        Text_DNI = new javax.swing.JLabel();
        Text_Sexo = new javax.swing.JLabel();
        Text_Apellido2 = new javax.swing.JLabel();
        Text_Nacionalidad = new javax.swing.JLabel();
        Text_Nacimiento = new javax.swing.JLabel();
        jText_Nombre = new javax.swing.JTextField();
        jText_Apellido1 = new javax.swing.JTextField();
        jText_Apellido2 = new javax.swing.JTextField();
        jTextDNI = new javax.swing.JTextField();
        jText_Nacionalidad = new javax.swing.JTextField();
        Radio_Hombre = new javax.swing.JRadioButton();
        Radio_Mujer = new javax.swing.JRadioButton();
        Dia = new javax.swing.JComboBox<>();
        Mes = new javax.swing.JComboBox<>();
        Año = new javax.swing.JComboBox<>();
        Boton_Siguiente = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text_Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_Nombre.setText("Nombre");
        jPanel1.add(Text_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        Text_Apellido1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_Apellido1.setText("Primer Apellido");
        jPanel1.add(Text_Apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        Text_DNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_DNI.setText("DNI");
        jPanel1.add(Text_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        Text_Sexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_Sexo.setText("Sexo");
        jPanel1.add(Text_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        Text_Apellido2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_Apellido2.setText("Segundo Apellido");
        jPanel1.add(Text_Apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        Text_Nacionalidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_Nacionalidad.setText("Nacionalidad");
        jPanel1.add(Text_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 20));

        Text_Nacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_Nacimiento.setText("Fecha de Nacimiento");
        jPanel1.add(Text_Nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jText_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_NombreActionPerformed(evt);
            }
        });
        jPanel1.add(jText_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));
        jPanel1.add(jText_Apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 170, 30));
        jPanel1.add(jText_Apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, 30));
        jPanel1.add(jTextDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 30));
        jPanel1.add(jText_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 170, 30));

        buttonGroup1.add(Radio_Hombre);
        Radio_Hombre.setText("Hombre");
        jPanel1.add(Radio_Hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        buttonGroup1.add(Radio_Mujer);
        Radio_Mujer.setText("Mujer");
        Radio_Mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_MujerActionPerformed(evt);
            }
        });
        jPanel1.add(Radio_Mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 50, -1));

        Año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917" }));
        jPanel1.add(Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        Boton_Siguiente.setText("Siguiente paso");
        Boton_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 450, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_NombreActionPerformed

    private void Radio_MujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_MujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_MujerActionPerformed

    private void Boton_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SiguienteActionPerformed
        // TODO add your handling code here:
    String sexo;
    boolean seleccionado=Radio_Hombre.isSelected();
       
    if(seleccionado==true){
           sexo="Hombre";
       }else{
        sexo="Mujer";
    }
        
         
    String nombre=jText_Nombre.getText();
    String papellido=jText_Apellido1.getText();    
    String sapellido=jText_Apellido2.getText();    
    String dni=jTextDNI.getText();    
    String nacionalidad=jText_Nacionalidad.getText();
    
    int d=Dia.getSelectedIndex();
    String dia=Dia.getItemAt(d);
    
    int m=Mes.getSelectedIndex();
    String mes=Mes.getItemAt(m);
    
    int a=Año.getSelectedIndex();
    String año=Año.getItemAt(a);
    
    String fecha=dia+"/"+mes+"/"+año;
    System.out.println(fecha);
    
     Connection conn=null;
   conectar con= new conectar(); 
   conn=con.getConnection();
        try{
     Statement st=conn.createStatement();
     String billete="insert into Billetes(DNI,Nombre,Primer_Apellido,Segundo_Apellido,Nacionalidad,Sexo,Fecha_de_nacimiento)values('"+dni+"','"+nombre+"','"+papellido+"','"+sapellido+"','"+nacionalidad+"','"+sexo+"','"+fecha+"')";
      st.executeUpdate(billete);
      System.out.println("Se ha creado el nuevo registro");
      datos da=new datos();
      da.setDNI(dni);
        }catch(Exception e){
            System.out.println("Error creando el registro: "+e);
        }
        
        this.setVisible(false);
        Asiento asi=new Asiento();
        asi.setVisible(true);
       
    }//GEN-LAST:event_Boton_SiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billetes_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billetes_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billetes_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billetes_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billetes_Personas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Año;
    private javax.swing.JToggleButton Boton_Siguiente;
    private javax.swing.JComboBox<String> Dia;
    private javax.swing.JComboBox<String> Mes;
    private javax.swing.JRadioButton Radio_Hombre;
    private javax.swing.JRadioButton Radio_Mujer;
    private javax.swing.JLabel Text_Apellido1;
    private javax.swing.JLabel Text_Apellido2;
    private javax.swing.JLabel Text_DNI;
    private javax.swing.JLabel Text_Nacimiento;
    private javax.swing.JLabel Text_Nacionalidad;
    private javax.swing.JLabel Text_Nombre;
    private javax.swing.JLabel Text_Sexo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jText_Apellido1;
    private javax.swing.JTextField jText_Apellido2;
    private javax.swing.JTextField jText_Nacionalidad;
    private javax.swing.JTextField jText_Nombre;
    // End of variables declaration//GEN-END:variables
}
