/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tercer_trimestre;

import datos.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import metodo.conectar;

/**
 *
 * @author artur
 */
public class ComprarBilletes extends javax.swing.JFrame {

    /**
     * Creates new form ComprarBilletes
     */
    public ComprarBilletes() {
        initComponents();

        Calendar min = Calendar.getInstance();
        min.set(Calendar.YEAR, 2017);
        min.set(Calendar.MONTH, 5);
        min.set(Calendar.DATE, 11);
        dateChooserPanel1.setMinDate(min);
        Calendar max = Calendar.getInstance();
        max.set(Calendar.YEAR, 2017);
        max.set(Calendar.MONTH, 6);
        max.set(Calendar.DATE, 13);
        dateChooserPanel1.setMaxDate(max);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Origen_Combo = new javax.swing.JComboBox<>();
        Destino_Combo = new javax.swing.JComboBox<>();
        Origen_Text = new javax.swing.JLabel();
        Destino_Text = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Siguiente_Boton = new javax.swing.JButton();
        Billetes_Text = new javax.swing.JLabel();
        Billetes_Field = new javax.swing.JTextField();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Origen_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigo", "Barcelona", "Santander", "Madrid", "Sevilla", "Pamplona", "Valencia", "Bilbao", "Albacete", "Zaragoza", "Murcia", "Oviedo", "Tenerife", "Palma de Mallorca", "Badajoz", "Mérida", "Logroño" }));
        Origen_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origen_ComboActionPerformed(evt);
            }
        });
        jPanel1.add(Origen_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, 40));

        Destino_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigo", "Barcelona", "Santander", "Madrid", "Sevilla", "Pamplona", "Valencia", "Bilbao", "Albacete", "Zaragoza", "Murcia", "Oviedo", "Tenerife", "Palma de Mallorca", "Badajoz", "Mérida", "Logroño" }));
        Destino_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destino_ComboActionPerformed(evt);
            }
        });
        jPanel1.add(Destino_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 110, 40));

        Origen_Text.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Origen_Text.setText("Origen");
        jPanel1.add(Origen_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        Destino_Text.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Destino_Text.setText("Destino");
        jPanel1.add(Destino_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 570, -1));

        Siguiente_Boton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Siguiente_Boton.setText("Siguiente paso");
        Siguiente_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Siguiente_BotonActionPerformed(evt);
            }
        });
        jPanel1.add(Siguiente_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        Billetes_Text.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Billetes_Text.setText("Número de billetes:");
        jPanel1.add(Billetes_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        jPanel1.add(Billetes_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 130, 30));
        jPanel1.add(dateChooserPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 350, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Siguiente_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Siguiente_BotonActionPerformed
        // TODO add your handling code here:
        Iterable seleccion = dateChooserPanel1.getSelection();
        String dia = String.valueOf(seleccion);

        //hacer libreria
        String diaremplazado = dia.replace("[", "").replace("]", "");
        StringBuffer sb = new StringBuffer(diaremplazado);
        sb.insert(6, "20");
        //hasta aqui

        String selorigen = (String) Origen_Combo.getSelectedItem();

        String seldestino = (String) Destino_Combo.getSelectedItem();

        Connection conn = null;
        conectar con = new conectar();
        conn = con.getConnection();

        try {

            String vuelo = "SELECT * from Vuelos where Origen='" + selorigen + "' and Destino='" + seldestino + "' and Fecha_Salida='" + sb + "'";

            Statement st = conn.createStatement();
            ResultSet vue = st.executeQuery(vuelo);

            while (vue.next()) {
                String id = vue.getString("Id");
                String origen = vue.getString("Origen");
                String destino = vue.getString("Destino");
                String aerolinea = vue.getString("Aerolinea");
                String fecha = vue.getString("Fecha_Salida");
                String hora = vue.getString("Hora_Salida");
                String precio = vue.getString("Precio") + "€";

                datos da = new datos();
                da.setDatos(id, origen, destino, aerolinea, fecha, hora, precio);
                da.setCodigo(id);
                da.setPrecio(precio);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }

        String bi = Billetes_Field.getText();
        int billetes = Integer.parseInt(bi);
        datos da = new datos();
        da.setnumBilletes(billetes);

        Interfaz_Datos inte = new Interfaz_Datos();
        inte.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_Siguiente_BotonActionPerformed

    private void Origen_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origen_ComboActionPerformed
        // TODO add your handling code here:
        int seleccion = Origen_Combo.getSelectedIndex();
        if (seleccion > 1) {
            Destino_Combo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_Origen_ComboActionPerformed

    private void Destino_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destino_ComboActionPerformed
        // TODO add your handling code here:
        int seleccion = Destino_Combo.getSelectedIndex();
        if (seleccion > 1) {
            Origen_Combo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_Destino_ComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarBilletes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarBilletes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarBilletes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarBilletes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprarBilletes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Billetes_Field;
    private javax.swing.JLabel Billetes_Text;
    private javax.swing.JComboBox<String> Destino_Combo;
    private javax.swing.JLabel Destino_Text;
    private javax.swing.JComboBox<String> Origen_Combo;
    private javax.swing.JLabel Origen_Text;
    private javax.swing.JButton Siguiente_Boton;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
